import type { Metadata } from "next";
import Image from "next/image";

import "./globals.css";
import { Krona_One, Poppins } from "@next/font/google"; // Import the fonts

// Configure the fonts
const krona = Krona_One({
  subsets: ["latin"],
  weight: "400",
});

const poppins = Poppins({
  weight: ["400", "700"], // Specify the font weights you need
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pushkar Dutta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="fixed inset-0">
          <Image
            src="/bgmain.png"
            alt="Background image"
            layout="fill"
            objectFit="cover"
            quality={100}
          />
        </div>
        {children}
      </body>
    </html>
  );
}
